In [1]:
import pandas as pd
import numpy as np
import os
from art_track_loader import track_loader as trl
from art_track_features import track_features as trf
from tensorflow import keras
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder, MinMaxScaler, OrdinalEncoder
from sklearn.metrics import f1_score, accuracy_score, roc_curve, precision_recall_curve, PrecisionRecallDisplay, roc_auc_score, plot_roc_curve, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay, plot_confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [2]:
def readdataframe(path):
    tracks_df = trl.get_tracks_from_csv_folder(path)
    track_series = trl.group_tracks(tracks_df)
    track_series = trf.calculate_and_include_all_features(track_series)
    visualisation_df = pd.concat(track_series.tolist())
    visualisation_df = visualisation_df.dropna()
    return visualisation_df

In [47]:
path = 'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/dddrone/'
file_names = os.listdir(path)  # load all filenames in path
print(file_names[0])

A12B6EE58C4M5P88IHA53M7P4_20211215_ContextId_15_TrackId_11007_2021-12-15_11-34_NotAvailable.csv

In [48]:
# Read all csv files in the Drone folder
tracks_df = trl.get_tracks_from_csv_folder(path)
# Group tracks by 'ContextID', 'ScenarioTrackID'
track_series = trl.group_tracks(tracks_df)

In [49]:
d1, d2, d3, d4, d5 = 797, 1162, 833, 733, 1033

drone_fold_1 = tracks_df[0:d1].drop(['Unnamed: 0'], axis=1)
drone_fold_2 = tracks_df[d1:d1+d2].drop(['Unnamed: 0'], axis=1)
drone_fold_3 = tracks_df[d1+d2:d1+d2+d3].drop(['Unnamed: 0'], axis=1)
drone_fold_4 = tracks_df[d1+d2+d3:d1+d2+d3+d4].drop(['Unnamed: 0'], axis=1)
drone_fold_5 = tracks_df[d1+d2+d3+d4:d1+d2+d3+d4+d5].drop(['Unnamed: 0'], axis=1)

In [10]:
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Drone track number is',track_series[i]['ID'][a])
    print('Number of points is',len(track_series[i]['ID']))
# print(len(track_series))

Drone track number is 34
Number of points is 25
Drone track number is 40
Number of points is 103
Drone track number is 84
Number of points is 9
Drone track number is 88
Number of points is 54
Drone track number is 103
Number of points is 113
Drone track number is 170
Number of points is 212
Drone track number is 202
Number of points is 147
Drone track number is 21
Number of points is 66
Drone track number is 64
Number of points is 26
Drone track number is 102
Number of points is 11
Drone track number is 106
Number of points is 8
Drone track number is 117
Number of points is 5
Drone track number is 120
Number of points is 10
Drone track number is 129
Number of points is 2
Drone track number is 325
Number of points is 12
Drone track number is 510
Number of points is 4
Drone track number is 521
Number of points is 11
Drone track number is 524
Number of points is 16
Drone track number is 538
Number of points is 4
Drone track number is 613
Number of points is 15
Drone track number is 636
Number of points is 4
Drone track number is 646
Number of points is 4
Drone track number is 825
Number of points is 12
Drone track number is 833
Number of points is 20
Drone track number is 1378
Number of points is 11
Drone track number is 1387
Number of points is 11
Drone track number is 1464
Number of points is 11
Drone track number is 1466
Number of points is 10
Drone track number is 1470
Number of points is 11
Drone track number is 1478
Number of points is 8
Drone track number is 1496
Number of points is 11
Drone track number is 1500
Number of points is 7
Drone track number is 1512
Number of points is 5
Drone track number is 1524
Number of points is 6
Drone track number is 1532
Number of points is 11
Drone track number is 1537
Number of points is 11
Drone track number is 1618
Number of points is 6
Drone track number is 1691
Number of points is 11
Drone track number is 3219
Number of points is 11
Drone track number is 3227
Number of points is 11
Drone track number is 3248
Number of points is 8
Drone track number is 3250
Number of points is 11
Drone track number is 3266
Number of points is 11
Drone track number is 3285
Number of points is 11
Drone track number is 3290
Number of points is 11
Drone track number is 3297
Number of points is 10
Drone track number is 3315
Number of points is 11
Drone track number is 4143
Number of points is 2
Drone track number is 4152
Number of points is 10
Drone track number is 4164
Number of points is 8
Drone track number is 4217
Number of points is 28
Drone track number is 4233
Number of points is 28
Drone track number is 4235
Number of points is 26
Drone track number is 4339
Number of points is 23
Drone track number is 4352
Number of points is 4
Drone track number is 4400
Number of points is 31
Drone track number is 4404
Number of points is 11
Drone track number is 4441
Number of points is 22
Drone track number is 4452
Number of points is 53
Drone track number is 4999
Number of points is 40
Drone track number is 5026
Number of points is 5
Drone track number is 5032
Number of points is 16
Drone track number is 5037
Number of points is 21
Drone track number is 5091
Number of points is 14
Drone track number is 5124
Number of points is 8
Drone track number is 5133
Number of points is 5
Drone track number is 5140
Number of points is 10
Drone track number is 5181
Number of points is 11
Drone track number is 5195
Number of points is 6
Drone track number is 5200
Number of points is 11
Drone track number is 5214
Number of points is 10
Drone track number is 5221
Number of points is 19
Drone track number is 8499
Number of points is 22
Drone track number is 8501
Number of points is 4
Drone track number is 8529
Number of points is 8
Drone track number is 8542
Number of points is 10
Drone track number is 8551
Number of points is 4
Drone track number is 8554
Number of points is 52
Drone track number is 8560
Number of points is 3
Drone track number is 148
Number of points is 11
Drone track number is 156
Number of points is 11
Drone track number is 179
Number of points is 8
Drone track number is 498
Number of points is 11
Drone track number is 505
Number of points is 11
Drone track number is 548
Number of points is 5
Drone track number is 631
Number of points is 11
Drone track number is 633
Number of points is 8
Drone track number is 652
Number of points is 13
Drone track number is 831
Number of points is 11
Drone track number is 837
Number of points is 9
Drone track number is 840
Number of points is 11
Drone track number is 2084
Number of points is 9
Drone track number is 3767
Number of points is 431
Drone track number is 4537
Number of points is 11
Drone track number is 4681
Number of points is 46
Drone track number is 4776
Number of points is 32
Drone track number is 4859
Number of points is 56
Drone track number is 5284
Number of points is 72
Drone track number is 5881
Number of points is 372
Drone track number is 6507
Number of points is 13
Drone track number is 6563
Number of points is 273
Drone track number is 7654
Number of points is 447
Drone track number is 3038
Number of points is 675
Drone track number is 11007
Number of points is 214
Drone track number is 13470
Number of points is 144

In [50]:
track_series = trl.group_tracks(drone_fold_1)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Drone track number in fold 1 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 1 is', len(track_series))

Drone track number in fold 1 is 34
Number of points is 25
Drone track number in fold 1 is 40
Number of points is 103
Drone track number in fold 1 is 84
Number of points is 9
Drone track number in fold 1 is 88
Number of points is 54
Drone track number in fold 1 is 103
Number of points is 113
Drone track number in fold 1 is 170
Number of points is 212
Drone track number in fold 1 is 202
Number of points is 147
Drone track number in fold 1 is 21
Number of points is 66
Drone track number in fold 1 is 102
Number of points is 11
Drone track number in fold 1 is 120
Number of points is 10
Drone track number in fold 1 is 325
Number of points is 12
Drone track number in fold 1 is 613
Number of points is 15
Drone track number in fold 1 is 636
Number of points is 4
Drone track number in fold 1 is 646
Number of points is 4
Drone track number in fold 1 is 825
Number of points is 12
The number of tracks in fold 1 is 15

In [51]:
track_series = trl.group_tracks(drone_fold_2)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Drone track number in fold 2 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 2 is', len(track_series))

Drone track number in fold 2 is 64
Number of points is 26
Drone track number in fold 2 is 106
Number of points is 8
Drone track number in fold 2 is 117
Number of points is 5
Drone track number in fold 2 is 129
Number of points is 2
Drone track number in fold 2 is 510
Number of points is 4
Drone track number in fold 2 is 521
Number of points is 11
Drone track number in fold 2 is 524
Number of points is 16
Drone track number in fold 2 is 538
Number of points is 4
Drone track number in fold 2 is 833
Number of points is 20
Drone track number in fold 2 is 1378
Number of points is 11
Drone track number in fold 2 is 1387
Number of points is 11
Drone track number in fold 2 is 1464
Number of points is 11
Drone track number in fold 2 is 1466
Number of points is 10
Drone track number in fold 2 is 1470
Number of points is 11
Drone track number in fold 2 is 1478
Number of points is 8
Drone track number in fold 2 is 1496
Number of points is 11
Drone track number in fold 2 is 1500
Number of points is 7
Drone track number in fold 2 is 1512
Number of points is 5
Drone track number in fold 2 is 1524
Number of points is 6
Drone track number in fold 2 is 1532
Number of points is 11
Drone track number in fold 2 is 1537
Number of points is 11
Drone track number in fold 2 is 1618
Number of points is 6
Drone track number in fold 2 is 1691
Number of points is 11
Drone track number in fold 2 is 3219
Number of points is 11
Drone track number in fold 2 is 3227
Number of points is 11
Drone track number in fold 2 is 3248
Number of points is 8
Drone track number in fold 2 is 3250
Number of points is 11
Drone track number in fold 2 is 3266
Number of points is 11
Drone track number in fold 2 is 3285
Number of points is 11
Drone track number in fold 2 is 3290
Number of points is 11
Drone track number in fold 2 is 3297
Number of points is 10
Drone track number in fold 2 is 3315
Number of points is 11
Drone track number in fold 2 is 4143
Number of points is 2
Drone track number in fold 2 is 4152
Number of points is 10
Drone track number in fold 2 is 4164
Number of points is 8
Drone track number in fold 2 is 4217
Number of points is 28
Drone track number in fold 2 is 4233
Number of points is 28
Drone track number in fold 2 is 4235
Number of points is 26
Drone track number in fold 2 is 4339
Number of points is 23
Drone track number in fold 2 is 4352
Number of points is 4
Drone track number in fold 2 is 4400
Number of points is 31
Drone track number in fold 2 is 4441
Number of points is 22
Drone track number in fold 2 is 4999
Number of points is 40
Drone track number in fold 2 is 5026
Number of points is 5
Drone track number in fold 2 is 5032
Number of points is 16
Drone track number in fold 2 is 5037
Number of points is 21
Drone track number in fold 2 is 5091
Number of points is 14
Drone track number in fold 2 is 5124
Number of points is 8
Drone track number in fold 2 is 5133
Number of points is 5
Drone track number in fold 2 is 5140
Number of points is 10
Drone track number in fold 2 is 5181
Number of points is 11
Drone track number in fold 2 is 5195
Number of points is 6
Drone track number in fold 2 is 5200
Number of points is 11
Drone track number in fold 2 is 5214
Number of points is 10
Drone track number in fold 2 is 5221
Number of points is 19
Drone track number in fold 2 is 631
Number of points is 11
Drone track number in fold 2 is 633
Number of points is 8
Drone track number in fold 2 is 652
Number of points is 13
Drone track number in fold 2 is 831
Number of points is 11
Drone track number in fold 2 is 2084
Number of points is 9
Drone track number in fold 2 is 3767
Number of points is 431
The number of tracks in fold 2 is 61

In [32]:
track_series = trl.group_tracks(drone_fold_3)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Drone track number in fold 3 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 3 is', len(track_series))

Drone track number in fold 3 is 4404
Number of points is 11
Drone track number in fold 3 is 4452
Number of points is 53
Drone track number in fold 3 is 8499
Number of points is 22
Drone track number in fold 3 is 8501
Number of points is 4
Drone track number in fold 3 is 8529
Number of points is 8
Drone track number in fold 3 is 8542
Number of points is 10
Drone track number in fold 3 is 8551
Number of points is 4
Drone track number in fold 3 is 8554
Number of points is 52
Drone track number in fold 3 is 8560
Number of points is 3
Drone track number in fold 3 is 148
Number of points is 11
Drone track number in fold 3 is 156
Number of points is 11
Drone track number in fold 3 is 179
Number of points is 8
Drone track number in fold 3 is 498
Number of points is 11
Drone track number in fold 3 is 505
Number of points is 11
Drone track number in fold 3 is 548
Number of points is 5
Drone track number in fold 3 is 837
Number of points is 9
Drone track number in fold 3 is 840
Number of points is 11
Drone track number in fold 3 is 4537
Number of points is 11
Drone track number in fold 3 is 4681
Number of points is 46
Drone track number in fold 3 is 4776
Number of points is 32
Drone track number in fold 3 is 4859
Number of points is 56
Drone track number in fold 3 is 5284
Number of points is 72
Drone track number in fold 3 is 5881
Number of points is 372
The number of tracks in fold 3 is 23

In [52]:
track_series = trl.group_tracks(drone_fold_4)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Drone track number in fold 4 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 4 is', len(track_series))

Drone track number in fold 4 is 6507
Number of points is 13
Drone track number in fold 4 is 6563
Number of points is 273
Drone track number in fold 4 is 7654
Number of points is 447
The number of tracks in fold 4 is 3

In [53]:
track_series = trl.group_tracks(drone_fold_5)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Drone track number in fold 5 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 5 is', len(track_series))

Drone track number in fold 5 is 3038
Number of points is 675
Drone track number in fold 5 is 11007
Number of points is 214
Drone track number in fold 5 is 13470
Number of points is 144
The number of tracks in fold 5 is 3

In [96]:
drone_fold_1.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/drone_fold_1.csv')
drone_fold_2.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/drone_fold_2.csv')
drone_fold_3.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/drone_fold_3.csv')
drone_fold_4.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/drone_fold_4.csv')
drone_fold_5.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/drone_fold_5.csv')

In [25]:
path = 'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/bbbird/'
# Read all csv files in the Bird folder
tracks_df = trl.get_tracks_from_csv_folder(path)
# Group tracks by 'ContextID', 'ScenarioTrackID'
track_series = trl.group_tracks(tracks_df)

In [41]:
b1, b2, b3, b4, b5 = 1035, 1036, 1189, 1152, 762
bird_fold_1 = tracks_df[0:b1].drop(['Unnamed: 0'], axis=1)
bird_fold_2 = tracks_df[b1:b1+b2].drop(['Unnamed: 0'], axis=1)
bird_fold_3 = tracks_df[b1+b2:b1+b2+b3].drop(['Unnamed: 0'], axis=1)
bird_fold_4 = tracks_df[b1+b2+b3:b1+b2+b3+b4].drop(['Unnamed: 0'], axis=1)
bird_fold_5 = tracks_df[b1+b2+b3+b4:b1+b2 +
                        b3+b4+b5].drop(['Unnamed: 0'], axis=1)

In [40]:
bird_fold_1.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/bird_fold_1.csv')
bird_fold_2.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/bird_fold_2.csv')
bird_fold_3.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/bird_fold_3.csv')
bird_fold_4.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/bird_fold_4.csv')
bird_fold_5.to_csv(
    'F:/pythonNotebook/art-ms3-art-track-classifier-dataset/KFold_CV/bird_fold_5.csv')

In [29]:
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Bird track number is',track_series[i]['ID'][a])
    print('Number of points is',len(track_series[i]['ID']))
# print(len(track_series))

Bird track number is 63406
Number of points is 205
Bird track number is 65917
Number of points is 33
Bird track number is 70431
Number of points is 143
Bird track number is 77520
Number of points is 75
Bird track number is 89989
Number of points is 77
Bird track number is 2008
Number of points is 55
Bird track number is 1515
Number of points is 51
Bird track number is 1926
Number of points is 54
Bird track number is 3237
Number of points is 71
Bird track number is 3824
Number of points is 271
Bird track number is 12576
Number of points is 928
Bird track number is 13303
Number of points is 12
Bird track number is 17073
Number of points is 96
Bird track number is 17612
Number of points is 54
Bird track number is 35140
Number of points is 50
Bird track number is 35875
Number of points is 14
Bird track number is 35885
Number of points is 13
Bird track number is 36046
Number of points is 18
Bird track number is 36155
Number of points is 34
Bird track number is 36258
Number of points is 182
Bird track number is 36319
Number of points is 29
Bird track number is 36506
Number of points is 37
Bird track number is 36596
Number of points is 163
Bird track number is 36978
Number of points is 59
Bird track number is 37302
Number of points is 29
Bird track number is 37591
Number of points is 104
Bird track number is 38684
Number of points is 126
Bird track number is 38729
Number of points is 81
Bird track number is 41318
Number of points is 196
Bird track number is 41499
Number of points is 76
Bird track number is 41859
Number of points is 47
Bird track number is 41919
Number of points is 31
Bird track number is 43028
Number of points is 75
Bird track number is 43157
Number of points is 16
Bird track number is 43197
Number of points is 20
Bird track number is 43406
Number of points is 23
Bird track number is 58102
Number of points is 566
Bird track number is 175107
Number of points is 298
Bird track number is 195016
Number of points is 241
Bird track number is 197493
Number of points is 78
Bird track number is 197544
Number of points is 37
Bird track number is 197613
Number of points is 38
Bird track number is 214523
Number of points is 27
Bird track number is 214663
Number of points is 211
Bird track number is 216468
Number of points is 23
Bird track number is 217081
Number of points is 107

In [36]:
track_series = trl.group_tracks(bird_fold_1)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Bird track number in fold 1 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 1 is', len(track_series))

Bird track number in fold 1 is 63406
Number of points is 205
Bird track number in fold 1 is 65917
Number of points is 33
Bird track number in fold 1 is 70431
Number of points is 143
Bird track number in fold 1 is 77520
Number of points is 75
Bird track number in fold 1 is 89989
Number of points is 77
Bird track number in fold 1 is 2008
Number of points is 55
Bird track number in fold 1 is 1515
Number of points is 51
Bird track number in fold 1 is 1926
Number of points is 54
Bird track number in fold 1 is 3237
Number of points is 71
Bird track number in fold 1 is 3824
Number of points is 271
The number of tracks in fold 1 is 10

In [37]:
track_series = trl.group_tracks(bird_fold_2)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Bird track number in fold 2 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 2 is', len(track_series))

Bird track number in fold 2 is 12576
Number of points is 928
Bird track number in fold 2 is 13303
Number of points is 12
Bird track number in fold 2 is 17073
Number of points is 96
The number of tracks in fold 2 is 3

In [38]:
track_series = trl.group_tracks(bird_fold_3)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Bird track number in fold 3 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 3 is', len(track_series))

Bird track number in fold 3 is 17612
Number of points is 54
Bird track number in fold 3 is 35140
Number of points is 50
Bird track number in fold 3 is 35875
Number of points is 14
Bird track number in fold 3 is 35885
Number of points is 13
Bird track number in fold 3 is 36046
Number of points is 18
Bird track number in fold 3 is 36155
Number of points is 34
Bird track number in fold 3 is 36258
Number of points is 182
Bird track number in fold 3 is 36319
Number of points is 29
Bird track number in fold 3 is 36506
Number of points is 37
Bird track number in fold 3 is 36596
Number of points is 163
Bird track number in fold 3 is 36978
Number of points is 59
Bird track number in fold 3 is 37302
Number of points is 29
Bird track number in fold 3 is 37591
Number of points is 104
Bird track number in fold 3 is 38684
Number of points is 126
Bird track number in fold 3 is 38729
Number of points is 81
Bird track number in fold 3 is 41318
Number of points is 196
The number of tracks in fold 3 is 16

In [39]:
track_series = trl.group_tracks(bird_fold_4)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Bird track number in fold 4 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 4 is', len(track_series))

Bird track number in fold 4 is 41499
Number of points is 76
Bird track number in fold 4 is 41859
Number of points is 47
Bird track number in fold 4 is 41919
Number of points is 31
Bird track number in fold 4 is 43028
Number of points is 75
Bird track number in fold 4 is 43157
Number of points is 16
Bird track number in fold 4 is 43197
Number of points is 20
Bird track number in fold 4 is 43406
Number of points is 23
Bird track number in fold 4 is 58102
Number of points is 566
Bird track number in fold 4 is 175107
Number of points is 298
The number of tracks in fold 4 is 9

In [40]:
track_series = trl.group_tracks(bird_fold_5)
b = 0
for i in range(len(track_series)):
    a = track_series[i]['ID'].index[0]
    print('Bird track number in fold 5 is', track_series[i]['ID'][a])
    print('Number of points is', len(track_series[i]['ID']))
print('The number of tracks in fold 5 is', len(track_series))

Bird track number in fold 5 is 195016
Number of points is 241
Bird track number in fold 5 is 197493
Number of points is 78
Bird track number in fold 5 is 197544
Number of points is 37
Bird track number in fold 5 is 197613
Number of points is 38
Bird track number in fold 5 is 214523
Number of points is 27
Bird track number in fold 5 is 214663
Number of points is 211
Bird track number in fold 5 is 216468
Number of points is 23
Bird track number in fold 5 is 217081
Number of points is 107
The number of tracks in fold 5 is 8